### ISSUE TITLE
EM credit reel: numbers 10 to 16 not saved

### ISSUE THREAD

**Issue by tweety231323** [vpinball/b2s-designer#8]
A backglass made in version 1.2 saved "em credit reel 2" image 0-16 in directb2s.
A backglass made in version 1.28.1 saved only EMR_CT2_0 to EMR_CT2_9.

Imported EM credit reel images are not saved at all in directb2s. (ImportedEMR_CT3_00).

**Comment by JockeJarre** [comment]
@tweety231323  Hello, I do not know you yet, but we have discussed this issue with Hauntfreaks and Cliffy on VPU as well and the new builds are tested ok. Release comes now. Thanks for reporting it!
